# Generated by Django 5.2.6 on 2025-09-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('service', 'Service'), ('project', 'Project'), ('blog', 'Blog'), ('career', 'Career'), ('gallery', 'Gallery'), ('contact', 'Contact')], max_length=180)),
                ('meta_title', models.CharField(max_length=180)),
                ('meta_keywords', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=180)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meta/')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
