# Generated by Django 5.2.6 on 2025-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'ordering': ['-id'], 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterField(
            model_name='meta',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('service', 'Service'), ('project', 'Project'), ('blog', 'Blog'), ('career', 'Career'), ('gallery', 'Gallery'), ('contact', 'Contact')], max_length=180),
        ),
    ]
