# Generated by Django 5.2.6 on 2025-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_clientlogo_herobanner_projectcategory_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
