# Generated by Django 5.2.6 on 2025-09-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blog_meta_description_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='meta_description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
