# Generated by Django 5.2.6 on 2025-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_project_options_project_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order_id'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='order_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
