# Generated by Django 5.2.6 on 2025-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_project_date_project_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
