# Generated by Django 5.2.6 on 2025-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_service_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='launch_date',
        ),
        migrations.AddField(
            model_name='project',
            name='timescale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
