# Generated by Django 5.2.6 on 2025-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_date_project_launch_date_project_timescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='timescale',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
