# Generated by Django 5.2.6 on 2025-09-13 09:26

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_project_client_alter_project_timescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('experience', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('opening', models.PositiveIntegerField()),
                ('last_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='CareerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.career', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Career Enquiry',
                'verbose_name_plural': 'Career Enquiries',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
