# Generated by Django 5.2.6 on 2025-09-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_career_gallery_careerenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
