# Generated by Django 5.2.6 on 2025-09-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_career_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerenquiry',
            options={'verbose_name': 'Career Enquiry', 'verbose_name_plural': 'Career Enquiries'},
        ),
        migrations.RemoveField(
            model_name='careerenquiry',
            name='subject',
        ),
        migrations.AddField(
            model_name='careerenquiry',
            name='resume',
            field=models.FileField(default=1, upload_to='resume'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='careerenquiry',
            table=None,
        ),
    ]
