# Generated by Django 5.2.6 on 2025-09-15 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_careerenquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerenquiry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
