# Generated by Django 5.2.6 on 2025-09-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_careerenquiry_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Enquiry',
                'verbose_name_plural': 'Service Enquiries',
            },
        ),
    ]
